# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.ssh.username = "ansible"
  config.ssh.password = "root"

  config.vm.define "virtualbox" do |vb|
    vb.vm.hostname = "postgres"
    vb.vm.box = "romanow/ansible-box"
    vb.vm.box_version = "22.04"
    vb.vm.network :private_network, ip: "192.168.100.100"

    config.vm.provider :virtualbox do |vm|
      vm.memory = "4098"
      vm.cpus = "2"
    end

    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
      s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/ansible/.ssh/authorized_keys
      SHELL
    end
  end
end