server:
  port: 8080

spring:
  profiles.active: local
  application.name: database-partitioning
  main.banner-mode: off
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
  shell:
    history:
      enabled: false
